spring.application.name=spring-batch-v5

spring.datasource.JdbcUrl=jdbc:postgresql://localhost:5432/batch_db
spring.datasource.username=postgres
spring.datasource.password=123456

app.datasource.JdbcUrl=jdbc:postgresql://localhost:5432/app_batch
app.datasource.username=postgres
app.datasource.password=123456

spring.batch.jdbc.initialize-schema=always

#MAIL SENDER PROPS
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.startt.enable=true

spring.mail.username=5ad295c3bd372e
spring.mail.password=b8702c3a65e713